### ISSUE TITLE
Installtion is failed

### ISSUE THREAD

**Issue by GorSarg** [phozen/Virtual-JetDirect-Print-Server#1]
Hello, I am trying to install the print server but getting an error. Could you please assist me? What's wrong?
When the script asks for a username and password, I set the username/password from which I log into the system.
(windows 10)

The file is located at C:\Users\Admin\Downloads\VirtualJetDirectServer 0.1.0\VirtualJetDirectServer\VirtualJetDirectServer.InstallLog.
Rolling back assembly 'C:\Users\Admin\Downloads\VirtualJetDirectServer 0.1.0\VirtualJetDirectServer\VirtualJetDirectServer.exe'.
Affected parameters are:
   logtoconsole =
   logfile = C:\Users\Admin\Downloads\VirtualJetDirectServer 0.1.0\VirtualJetDirectServer\VirtualJetDirectServer.InstallLog
   assemblypath = C:\Users\Admin\Downloads\VirtualJetDirectServer 0.1.0\VirtualJetDirectServer\VirtualJetDirectServer.exe
Restoring event log to previous state for source VirtualPrintServer.

The Rollback phase completed successfully.

The transacted install has completed.

Unhandled Exception: System.InvalidOperationException: The installation failed, and the rollback has been performed. ---> System.ComponentModel.Win32Exception: The account name is invalid or does not exist, or the password is invalid for the account name specified
   at System.ServiceProcess.ServiceInstaller.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.AssemblyInstaller.Install(IDictionary savedState)
   at System.Configuration.Install.Installer.Install(IDictionary stateSaver)
   at System.Configuration.Install.TransactedInstaller.Install(IDictionary savedState)
   --- End of inner exception stack trace ---
   at System.Configuration.Install.ManagedInstallerClass.InstallHelper(String[] args)

**Comment by jerome-duchene** [comment]
I think that you need to provide the username with the Windows domain. For example: composo\username

**Comment by GorSarg** [comment]
thanks. that worked
